parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Ra3s":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TYPES=void 0;const{i18n:{__:e}}=wp,l=[{label:e("Newest","buddypress"),value:"newest"},{label:e("Active","buddypress"),value:"active"},{label:e("Popular","buddypress"),value:"popular"},{label:e("Alphabetical","buddypress"),value:"alphabetical"}];exports.TYPES=l;
},{}],"l8fw":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./constants");const{blockEditor:{InspectorControls:t},components:{Disabled:l,PanelBody:o,RangeControl:r,SelectControl:n,TextControl:s,ToggleControl:a},element:{Fragment:u,createElement:i},i18n:{__:d},serverSideRender:p}=wp,b=({attributes:b,setAttributes:c})=>{const{title:g,maxGroups:m,groupDefault:y,linkTitle:C}=b;return i(u,null,i(t,null,i(o,{title:d("Settings","buddypress"),initialOpen:!0},i(s,{label:d("Title","buddypress"),value:g,onChange:e=>{c({title:e})}}),i(r,{label:d("Max groups to show","buddypress"),value:m,onChange:e=>c({maxGroups:e}),min:1,max:10,required:!0}),i(n,{label:d("Default groups to show","buddypress"),value:y,options:e.TYPES,onChange:e=>{c({groupDefault:e})}}),i(a,{label:d("Link block title to Groups directory","buddypress"),checked:!!C,onChange:()=>{c({linkTitle:!C})}}))),i(l,null,i(p,{block:"bp/dynamic-groups",attributes:b})))};var c=b;exports.default=c;
},{"./constants":"Ra3s"}],"SJlW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;const{blocks:{createBlock:e}}=wp,t={from:[{type:"block",blocks:["core/legacy-widget"],isMatch:({idBase:e,instance:t})=>!(null==t||!t.raw)&&"bp_groups_widget"===e,transform:({instance:t})=>e("bp/dynamic-groups",{title:t.raw.title,maxGroups:t.raw.max_groups,groupDefault:t.raw.group_default,linkTitle:t.raw.link_title})}]};var r=t;exports.default=r;
},{}],"lVvR":[function(require,module,exports) {
"use strict";var e=r(require("./dynamic-groups/edit")),t=r(require("./dynamic-groups/transforms"));function r(e){return e&&e.__esModule?e:{default:e}}const{blocks:{registerBlockType:s},i18n:{__:u}}=wp;s("bp/dynamic-groups",{title:u("Dynamic Groups List","buddypress"),description:u("A dynamic list of recently active, popular, newest, or alphabetical groups.","buddypress"),icon:{background:"#fff",foreground:"#d84800",src:"buddicons-groups"},category:"buddypress",attributes:{title:{type:"string",default:u("Groups","buddypress")},maxGroups:{type:"number",default:5},groupDefault:{type:"string",default:"active"},linkTitle:{type:"boolean",default:!1}},edit:e.default,transforms:t.default});
},{"./dynamic-groups/edit":"l8fw","./dynamic-groups/transforms":"SJlW"}]},{},["lVvR"], null)
//# sourceMappingURL=/bp-groups/js/blocks/dynamic-groups.js.map