<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Layout Settings', 'genesis' ); ?></h3>
<p>
	<?php esc_html_e( 'This lets you select the layout for the archive page. On most of the child themes you\'ll see these options:', 'genesis' ); ?>
</p>
<ul>
	<li><?php esc_html_e( 'Content Sidebar', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content Sidebar', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Content Sidebar Sidebar', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Sidebar Content', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Full Width Content', 'genesis' ); ?></li>
</ul>
<p>
	<?php esc_html_e( 'These options can be extended or limited by the child theme.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type\'s archive page.', 'genesis' ); ?>
</p>
