<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Blog Page', 'genesis' ); ?></h3>
<p>
	<?php esc_html_e( 'This works with the Blog Template, which is a page template that shows your latest posts. It\'s what people see when they land on your homepage.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'In the General Settings you can select a specific category to display from the drop down menu, and exclude categories by ID, or even select how many posts you\'d like to display on this page.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'There are some special features of the Blog Template that allow you to specify which category to show on each page using the template, which is helpful if you have a "News" category (or something else) that you want to display separately.', 'genesis' ); ?>
</p>
<p>
	<?php
	/* translators: 1: Open anchor tag, 2: Close anchor tag. */
	printf( esc_html__( 'You can find more on this feature in the %1$sHow to Add a Post Category Page tutorial.%2$s', 'genesis' ), '<a href="https://www.studiopress.com/tutorials/genesis/add-post-category-page" target="_blank" rel="noopener noreferrer">', '</a>' );
	?>
</p>
