<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Navigation', 'genesis' ); ?></h3>
<p>
	<?php esc_html_e( 'The Primary Navigation Extras typically display on the right side of your Primary Navigation menu.', 'genesis' ); ?>
</p>
<ul>
	<li><?php esc_html_e( 'Today\'s date displays the current date', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'RSS feed link displays a link to the RSS feed for your site that a reader can use to subscribe to your site using the feedreader of their choice.', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Search form displays a small search form utilizing the WordPress search functionality.', 'genesis' ); ?></li>
	<li><?php esc_html_e( 'Twitter link displays a link to your Twitter profile, as indicated in Twitter ID setting. Enter only your user name in this setting.', 'genesis' ); ?></li>
</ul>
<p>
	<?php esc_html_e( 'These options can be extended or limited by the child theme.', 'genesis' ); ?>
</p>
