<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Custom Feeds', 'genesis' ); ?></h3>
<p>
	<?php esc_html_e( 'If you use Feedburner to handle your rss feed(s) you can use this function to set your site\'s native feed to redirect to your Feedburner feed.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'By filling in the feed links calling for the main site feed, it will display as a link to Feedburner.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'By checking the "Redirect Feed" box, all traffic to default feed links will be redirected to the Feedburner link instead.', 'genesis' ); ?>
</p>
