<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Content Archives', 'genesis' ); ?></h3>
<p>
	<?php esc_html_e( 'In the Genesis Theme Settings you may change the site wide Content Archives options to control what displays in the site\'s Archives.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'Archives include any pages using the blog template, category pages, tag pages, date archive, author archives, and the latest posts if there is no custom home page.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'The first option allows you to display the entry content or the entry excerpt. The Display entry content setting will display the entire entry including HTML code up to the <!--more--> tag if used (this is HTML for the comment tag that is not displayed in the browser).', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'It may also be coupled with the second field "Limit content to [___] characters" to limit the content to a specific number of letters or spaces. This will strip any HTML, but allows for more precise and easily changed lengths than the excerpt.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'The Display entry excerpt setting will display the first 55 words of the entry after also stripping any included HTML or the manual/custom excerpt added in the edit screen.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'The \'Include featured image?\' setting allows you to show a thumbnail of the first attached image or currently set featured image.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'This option should not be used with the entry content unless the content is limited to avoid duplicate images.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'The \'Image Size\' list is populated by the available image sizes defined in the theme.', 'genesis' ); ?>
</p>
<p>
	<?php esc_html_e( 'Entry Pagination Technique allows you to select one of two navigation methods.', 'genesis' ); ?>
</p>
