<?php
$strings = array(
	'choose_image' => __( 'Choose Image', 'zephyr-project-manager' ),
	'delete_team_notice' => __( 'Are you sure you want to delete this team? This action cannot be undone.', 'zephyr-project-manager' ),
	'delete_task_notice' => __( 'Are you sure you want to delete this task? This action cannot be undone.', 'zephyr-project-manager' ),
	'loading_progress' => __( 'Loading progress...', 'zephyr-project-manager' ),
	'completed_projects' => __( 'Completed Projects', 'zephyr-project-manager' ),
	'pending_projects' => __( 'Pending Projects', 'zephyr-project-manager' ),
	'saving_changes' => __( 'Saving changes...', 'zephyr-project-manager' ),
	'select_csv' => __( 'Select a CSV File', 'zephyr-project-manager' ),
	'select_json' => __( 'Select a JSON File', 'zephyr-project-manager' ),
	'choose_file' => __( 'Choose File', 'zephyr-project-manager' ),
	'tasks_completed' => __( 'Tasks Completed', 'zephyr-project-manager' ),
	'tasks_remaining' => __( 'Tasks Remaining', 'zephyr-project-manager' ),
	'no_projects_found' => __( 'Oops, no projects found.', 'zephyr-project-manager' ),
	'no_users_found' => __( 'Oops, no users found.', 'zephyr-project-manager' ),
	'no_teams_found' => __( 'Oops, no teams found.', 'zephyr-project-manager' ),
	'enter_task_name' => __( 'Please enter a task name', 'zephyr-project-manager' ),
	'enter_project_name' => __( 'Please enter a project name', 'zephyr-project-manager' ),
	'saving' => __( 'Saving...', 'zephyr-project-manager' ),
	'save_changes' => __( 'Save Changes', 'zephyr-project-manager' ),
	'add_task' => __( 'Add Task', 'zephyr-project-manager' ),
	'file_link' => __( 'File Link', 'zephyr-project-manager' ),
	'file_info' => __( 'File Info', 'zephyr-project-manager' ),
	'task' => __( 'Task', 'zephyr-project-manager' ),
	'date_uploaded' => __( 'Date Uploaded', 'zephyr-project-manager' ),
	'delete_file_notice' => __( 'Are you sure you want to delete this file?', 'zephyr-project-manager' ),
	'file_removed' => __( 'File Removed', 'zephyr-project-manager' ),
	'new_subtask' => __( 'New Subtask', 'zephyr-project-manager' ),
	'create_new_task' => __( 'Create New Task', 'zephyr-project-manager' ),
	'task_description' => __( 'Task Description', 'zephyr-project-manager' ),
	'assignee' => __( 'Assignee', 'zephyr-project-manager' ),
	'subtasks' => __( 'Subtasks', 'zephyr-project-manager' ),
	'attachments' => __( 'Attachments', 'zephyr-project-manager' ),
	'start_date' => __( 'Start Date', 'zephyr-project-manager' ),
	'due_date' => __( 'Due Date', 'zephyr-project-manager' ),
	'include' => __( 'Include', 'zephyr-project-manager' ),
	'task_name' => __( 'Task Name', 'zephyr-project-manager' ),
	'project_name' => __( 'Project Name', 'zephyr-project-manager' ),
	'copy_of' => __( 'Copy of', 'zephyr-project-manager' ),
	'copy_task' => __( 'Copy Task', 'zephyr-project-manager' ),
	'copy_project' => __( 'Copy Project', 'zephyr-project-manager' ),
	'create_new_project' => __( 'Create New Project', 'zephyr-project-manager' ),
	'name' => __( 'Name', 'zephyr-project-manager' ),
	'description' => __( 'Description', 'zephyr-project-manager' ),
	'tasks' => __( 'Tasks', 'zephyr-project-manager' ),
	'project' => __( 'Project', 'zephyr-project-manager' ),
	'convert_task' => __( 'Convert Tasks', 'zephyr-project-manager' ),
	'assignee_as_creator' => __( 'Assignee as Project creator', 'zephyr-project-manager' ),
	'subtasks_as_tasks' => __( 'Subtasks as Tasks', 'zephyr-project-manager' ),
	'task_description_as_description' => __( 'Task Description as Project Description', 'zephyr-projects' ),
	'convert_to_project' => __( 'Convert Task to Project', 'zephyr-project-manager' ),
	'loading_tasks' => __( 'Loading tasks...', 'zephyr-project-manager' ),
	'close' => __( 'Close', 'zephyr-project-manager' ),
	'files' => __( 'Files', 'zephyr-project-manager' ),
	'upload_file' => __( 'Upload File', 'zephyr-project-manager' ),
	'import_tasks' => __( 'Import Tasks', 'zephyr-project-manager' ),
	'importing_via_csv' => __( 'Importing via CSV', 'zephyr-project-manager' ),
	'importing_via_json' => __( 'Importing via JSON', 'zephyr-project-manager' ),
	'importing' => __( 'Importing', 'zephyr-project-manager' ),
	'sending' => __( 'Sending...', 'zephyr-project-manager' ),
	'comment' => __( 'Comment', 'zephyr-project-manager' ),
	'delete' => __( 'Delete', 'zephyr-project-manager' ),
	'deleted' => __( 'deleted', 'zephyr-project-manager' ),
	'subtask_saved' => __( 'Subtask Saved', 'zephyr-project-manager' ),
	'subtask_deleted' => __( 'Subtask Deleted', 'zephyr-project-manager' ),
	'creating_subtask' => __( 'Creating Subtask', 'zephyr-project-manager' ),
	'changes_saved' => __( 'Changes Saved Successfully', 'zephyr-project-manager' ),
	'message_removed' => __( 'Message Removed', 'zephyr-project-manager' ),
	'uploading_file' => __( 'Uploading File', 'zephyr-project-manager' ),
	'uploading_files' => __( 'Uploading Files...', 'zephyr-project-manager' ),
	'file_uploaded' => __( 'File Uploaded', 'zephyr-project-manager' ),
	'task_exists' => __( 'Task already exists', 'zephyr-project-manager' ),
	'deleting_category' => __( 'Deleting Category...', 'zephyr-project-manager' ),
	'creating_category' => __( 'Creating Category...', 'zephyr-project-manager' ),
	'overview' => __( 'Overview', 'zephyr-project-manager' ),
	'tasks' => __( 'Tasks', 'zephyr-project-manager' ),
	'discussion' => __( 'Discussion', 'zephyr-project-manager' ),
	'due_tasks' => __( 'Due Tasks', 'zephyr-project-manager' ),
	'projects' => __( 'Projects', 'zephyr-project-manager' ),
	'all_projects' => __( 'All Projects', 'zephyr-project-manager' ),
	'archived_projects' => __( 'Archived Projects', 'zephyr-project-manager' ),
	'page' => __( 'Page', 'zephyr-project-manager' ),
	'access_updated' => __( 'Access updated', 'zephyr-project-manager' ),
	'pending_tasks' => __( 'Pending Tasks', 'zephyr-project-manager' ),
	'overdue_tasks' => __( 'Overdue Tasks', 'zephyr-project-manager' ),
	'completed_tasks' => __( 'Completed Tasks', 'zephyr-project-manager' ),
	'select_all' => __( 'Deselect All', 'zephyr-project-manager' ),
	'deselect_all' => __( 'Deselect All', 'zephyr-project-manager' ),
	'delete_category_notice' => __( 'Are you sure you want to permanently delete this category?', 'zephyr-project-manager' ),
	'incorrect_import' => __( 'It appears that you have not uploaded a CSV file or a JSON file. Please make sure that the file format is correct and try again.', 'zephyr-project-manager' ),
	'delete_project_notice' => __( 'Are you sure you want to delete this project and all of its tasks?', 'zephyr-project-manager' ),
	'no_projects_created' => sprintf( __( 'No projects created yet. To create a project, click on the \'Add\' button at the top right of the screen or click %s here %s', 'zephyr-project-manager' ), '<a id="zpm_first_project" class="zpm_button_link">', '</a>' ),
	'error_loading_tasks' => __( 'There was a problem loading the tasks for this project.', 'zephyr-project-manager' ),
	'error_creating_task' => __(  'There was a problem creating the task', 'zephyr-project-manager' ),
	'error_saving_task' => __( 'There was a problem saving the task.', 'zephyr-project-manager' ),
	'error_creating_project' => __( 'There was a problem adding the project.', 'zephyr-project-manager' ),
	'error_removing_message' => __( 'Problem removing message.', 'zephyr-project-manager' ),
	'error_copying_task' => __( 'There was a problem copying the task. Please try again.', 'zephyr-project-manager' ),
	'error_converting_task' => __( 'There was a problem converting the task', 'zephyr-project-manager' ),
	'error_exporting_task' => __( 'There was a problem exporting the task. Please try again.', 'zephyr-project-manager' ),
	'error_exporting_tasks' => __( 'There was a problem exporting the tasks. Please try again.', 'zephyr-project-manager' ),
	'task_created' => __( 'Task successfully created', 'zephyr-project-manager' ),
	'task_updated' => __( 'Task updated successfully.', 'zephyr-project-manager' ),
	'error_viewing_task' => __( 'There was a problem loading the task', 'zephyr-project-manager' ),
	'copying_project' => __( 'Copying project...', 'zephyr-project-manager' ),
	'error_copying_project' => __( 'There was an unexpected problem while copying the project', 'zephyr-project-manager' ),
	'project_copied' => __( 'Project successfully copied', 'zephyr-project-manager' ),
	'task_due_today' => __( 'You have a task that is due today', 'zephyr-project-manager' ),
	'task_due_tomorrow' => __( 'You have a task that is due tomorrow', 'zephyr-project-manager' ),
	'dismiss_notice' => __( 'Dismiss Notice', 'zephyr-project-manager' ),
	'select_assignee' => __( 'Select Assignee', 'zephyr-project-manager' ),
	'text_field' => __( 'Text Field', 'zephyr-project-manager' ),
	'number_field' => __( 'Number Field', 'zephyr-project-manager' ),
	'date_field' => __( 'Date Field', 'zephyr-project-manager' ),
	'select_field' => __( 'Select Field', 'zephyr-project-manager' ),
	'save_task' => __( 'Save Task', 'zephyr-project-manager' ),
	'loading' => __( 'Loading...', 'zephyr-project-manager' ),
	'creating_project' => __( 'Creating Project...', 'zephyr-project-manager' ),
	'project_created' => __( 'Project created successfully', 'zephyr-project-manager' ),
	'converting_to_project' => __( 'Converting task to project...', 'zephyr-project-manager' ),
	'new_project_created' => __( 'New project created', 'zephyr-project-manager' ),
	'go_to_project' => __( 'Go to Project', 'zephyr-project-manager' ),
	'no_date_set' => __( 'No date set', 'zephyr-project-manager' ),
	'printed_from_zephyr' => __( 'Printed from Zephyr Project Manager', 'zephyr-project-manager' ),
	'error_printing_tasks' => __( 'There was a problem printing the project.', 'zephyr-project-manager' ),
	'problem_occurred' => __( 'There was a problem. Please reload and try again.', 'zephyr-project-manager' ),
	'error_sending_message' => __( 'There was a problem sending your message. Please try again.', 'zephyr-project-manager' ),
	'error_exporting_project_csv' => __( 'There was a problem exporting the project to CSV.', 'zephyr-project-manager' ),
	'category_created' => __( 'Category created.', 'zephyr-project-manager' ),
	'error_creating_category' => __( 'There was a problem adding the category. Please try again.', 'zephyr-project-manager' ),
	'error_filtering' => __( 'There was a problem with the filtering.', 'zephyr-project-manager' ),
	'error_deleting_project' => __( 'There was a problem deleting the project.', 'zephyr-project-manager' ),
	'error_importing_file' => __( 'There was a problem importing the file. Please try again.', 'zephyr-project-manager' ),
	'category_deleted' => __( 'Category deleted.', 'zephyr-project-manager' ),
	'project_archived' => __( 'Project Archived', 'zephyr-project-manager' ),
	'project_unarchived' => __( 'Project Unarchived', 'zephyr-project-manager' ),
	'error_deleting_category' => __( 'There was a problem removing the category. Please try again.', 'zephyr-project-manager' ),
	'category_saved' => __( 'Category changes saved.', 'zephyr-project-manager' ),
	'error_saving_category' => __( 'There was a problem updating the category. Please try again.', 'zephyr-project-manager' ),
	'task_deleted' => __( 'Task deleted', 'zephyr-project-manager' ),
	'error_deleting_task' => __( 'Problem deleting task', 'zephyr-project-manager' ),
	'error_loading_project_tasks' => __( 'There was a problem loading the tasks for this project.', 'zephyr-project-manager' ),
	'removed_from_dashboard' => __( 'Project removed from the dashboard.', 'zephyr-project-manager' ),
	'added_to_dashboard' => __( 'Added to the dashboard.', 'zephyr-project-manager' ),
	'error_adding_to_dashboard' => __( 'There was a problem adding the project to the dashboard.', 'zephyr-project-manager' ),
	'adding_to_dashboard' => __( 'Removing project from dashboard.', 'zephyr-project-manager' ),
	'creating_task' => __( 'Creating task...', 'zephyr-project-manager' ),
	'members_saved' => __( 'Members saved', 'zephyr-project-manager' ),
	'project_status_saved' => __( 'Project status saved', 'zephyr-project-manager' ),
	'error_updating_status' => __( 'There was a problem updating the status.', 'zephyr-project-manager' ),
	'no_results_found' => __( 'No results found...', 'zephyr-project-manager' ),
	'no_templates_found' => __( 'No templates found...', 'zephyr-project-manager' ),
	'new_custom_field' => __( 'New Custom Field', 'zephyr-project-manager' ),
	'create_custom_field' => __( 'Create Custom Field', 'zephyr-project-manager' ),
	'required' => __( 'Required', 'zephyr-project-manager' ),
	'add_option' => __( 'Add Option', 'zephyr-project-manager' ),
	'default_value' => __( 'Default Value', 'zephyr-project-manager' ),
	'option_value' => __( 'Option Value', 'zephyr-project-manager' ),
	'cancel' => __( 'Cancel', 'zephyr-project-manager' ),
	'create' => __( 'Create', 'zephyr-project-manager' ),
	'no_chart_data' => __( 'There is no chart data to show.', 'zephyr-project-manager' ),
	'custom_field_delete_prompt' => __( 'Are you sure you want to permanently delete this custom field?', 'zephyr-project-manager' ),
	'template_delete_prompt' => __( 'Are you sure you want to permanently delete this template?', 'zephyr-project-manager' ),
	'shortcode_copied' => __( 'Shortcode copied to clipboard', 'zephyr-project-manager' ),
	'none' => __( 'None', 'zephyr-project-manager' ),
	'edit_message' => __( 'Edit Message', 'zephyr-project-manager' ),
	'textarea' => __( 'Textarea', 'zephyr-project-manager' ),
	'priority' => __( 'Priority', 'zephyr-project-manager' ),
	'new_column' => __( 'New Column', 'zephyr-project-manager' ),
    'add_new_task' => __( 'Add new task', 'zephyr-project-manager' ),
    'task_copied' => __( 'Task Copied', 'zephyr-project-manager' ),
    'copy_column' => __( 'Copy Column', 'zephyr-project-manager' ),
    'copy_column_to_project' => __( 'Copy Column to Project', 'zephyr-project-manager' ),
    'milestone' => __( 'Milestone', 'zephyr-project-manager' ),
	'achieved' => __( 'achieved', 'zephyr-project-manager' ),
    'delete_column' => __( 'Delete Column', 'zephyr-project-manager' ),
	'column_copied' => __( 'Column Copied', 'zephyr-project-manager' ),
	'no_attachments' => __( 'No attachments', 'zephyr-project-manager' ),
	'category' => __( 'Category', 'zephyr-project-manager' ),
	'delete_comment_prompt' => __( 'Are you sure you want to delete this message?', 'zephyr-project-manager' ),
	'delete_status_prompt' => __( 'Are you sure you want to delete this priority / status? This action cannot be undone.', 'zephyr-project-manager' ),
	'completed' => __( 'Completed', 'zephyr-project-manager' ),
    'button_text' => array(
    	'today' => __( 'Today', 'zephyr-project-manager' ),
    	'month' => __( 'Month', 'zephyr-project-manager' ),
		'week' => __( 'Week', 'zephyr-project-manager' ),
		'day' => __( 'Day', 'zephyr-project-manager' ),
		'list' => __( 'List', 'zephyr-project-manager' )
    ),
	'month_names' => [
		__( 'January', 'zephyr-project-manager' ), 
		__( 'February', 'zephyr-project-manager' ), 
		__( 'March', 'zephyr-project-manager' ), 
		__( 'April', 'zephyr-project-manager' ), 
		__( 'May', 'zephyr-project-manager' ), 
		__( 'June', 'zephyr-project-manager' ),
		__( 'July', 'zephyr-project-manager' ),
		__( 'August', 'zephyr-project-manager' ), 
		__( 'September', 'zephyr-project-manager' ), 
		__( 'October', 'zephyr-project-manager' ), 
		__( 'November', 'zephyr-project-manager' ), 
		__( 'December', 'zephyr-project-manager' )
	],
	'day_names' => [
		__( 'Sunday', 'zephyr-project-manager' ), 
		__( 'Monday', 'zephyr-project-manager' ),
		__( 'Tuesday', 'zephyr-project-manager' ),
		__( 'Wednesday', 'zephyr-project-manager' ),
		__( 'Thursday', 'zephyr-project-manager' ),
		__( 'Friday', 'zephyr-project-manager' ),
		__( 'Saturday', 'zephyr-project-manager' )
	],
    'day_names_short' => [
		__( 'Sun', 'zephyr-project-manager' ), 
		__( 'Mon', 'zephyr-project-manager' ),
		__( 'Tue', 'zephyr-project-manager' ),
		__( 'Wed', 'zephyr-project-manager' ),
		__( 'Thu', 'zephyr-project-manager' ),
		__( 'Fri', 'zephyr-project-manager' ),
		__( 'Sat', 'zephyr-project-manager' )
    ]
);

return apply_filters( 'zpm_admin_localized_strings', $strings );