<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-interactions',
	'deps' => [
		'elementor-v2-editor-controls',
		'elementor-v2-editor-elements',
		'elementor-v2-editor-mcp',
		'elementor-v2-editor-props',
		'elementor-v2-editor-responsive',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-events',
		'elementor-v2-icons',
		'elementor-v2-schema',
		'elementor-v2-session',
		'elementor-v2-ui',
		'elementor-v2-utils',
		'react',
		'wp-i18n',
	],
];
