<?php
/**
 * @package WP Static HTML Output
 *
 * Copyright (c) 2011 Leon Stafford
 */
?>

<div class="wrap">
	
	<h2><?= __('WP Static HTML Output Plugin', 'static-html-output-plugin');?></h2>
	
	<?php if (is_array($this->exportLog) && count($this->exportLog)): ?>
	<h3>Export Log</h3>
	<pre class="wpsho-export-log"><?php echo implode("\n", array_keys($this->exportLog)) ?></pre>
	<?php endif ?>
	
	<div class="postbox-container">
		<div class="metabox-holder">
			<div class="meta-box-sortables ui-sortable">
				
				<form id="general-options" method="post" action="">
					
					<div class="postbox">
						<div class="handlediv" title="Click to toggle"><br /></div>
						<h3 class="hndle"><span><?= __('Export Options', 'static-html-output-plugin');?></span></h3>
						<div class="inside">
							<p>
								<label for="baseUrl"><?= __('Base Url', 'static-html-output-plugin');?>:</label>
								<input type="text" id="baseUrl" name="baseUrl" value="<?php echo esc_attr($this->baseUrl) ?>" size="50" />
							</p>
							
							<p>
								<label for="additionalUrls"><?= __('Additional Urls', 'static-html-output-plugin');?>:</label>
								<textarea class="widefat" name="additionalUrls" id="additionalUrls" rows="5" cols="10"><?php echo esc_html($this->additionalUrls) ?></textarea>
							</p>
							
							<p>
								<input name="generateZip" id="generateZip" value="1" type="checkbox" <?php if ($this->generateZip == 1) echo "checked"; ?> />
								<label for="generateZip"><?= __('Generate Zip archive of whole site', 'static-html-output-plugin');?></label> 
							</p>							
								
							<p>
								<input name="retainStaticFiles" id="retainStaticFiles" value="1" type="checkbox" <?php if ($this->retainStaticFiles == 1) echo "checked"; ?> />
								<label for="retainStaticFiles"><?= __('Retain generated static files on server', 'static-html-output-plugin');?></label> 
							</p>
							
							<p>
								<input name="sendViaFTP" id="sendViaFTP" value="1" type="checkbox" <?php if ($this->sendViaFTP == 1) echo "checked"; ?> disabled />
								<label for="sendViaONECLICK"><?= __('One-Click Transfer to your own domain', 'static-html-output-plugin');?> <a href="#"><?= __('For VIP subscribers only', 'static-html-output-plugin');?></a></label>
								<br /><br /><b><span style="color:red;"><?= __('Become a VIP subcriber and receive:', 'static-html-output-plugin');?> </span></b>
                                                                <ul>
                                                                        <li>- Free domain name of your choosing (.com, .net, .org, etc)</li>
                                                                        <li>- One click deployment from your WordPress control panel</li>
                                                                        <li>- UNLIMITED filestorage for your whole WordPress site, including all attachments, etc.</li>
                                                                        <li>- Maximum redundancy so you never lose your static site</li>
                                                                        <li>- Premium support for the WP Static HTML Output Plugin via email with 24 hr response time</li>
                                                                </ul>
                                                                <b><span style="color:red;"><?= __('For pricing, terms and conditions, please contact:', 'static-html-output-plugin');?> </span></b> <a href="mailto:leon.stafford@mac.com">leon.stafford@mac.com</a>
                                                                                
							</p>

							<p>						
								<label for="ftpServer"><?= __('Your domain name', 'static-html-output-plugin');?>:</label><br />
								<input name="ftpServer" id="ftpServer" value="<?php echo esc_attr($this->ftpServer) ?>" size="30" />						
							</p>
							
							
							
							<p>						
								<label for="ftpPassword"><?= __('Your VIP code', 'static-html-output-plugin');?>:</label><br />
								<input name="ftpPassword" id="ftpPassword" type="password" value="" size="30" />						
							</p>	
							
                                                        <p class="submit">
                                                                
                                                                <input type="hidden" name="action" value="activate" />
                                                                <input class="button-primary" type="submit" name="submit" value="Activate VIP" onclick="alert('Please contact leon.stafford@mac.com for your VIP activation code.');return false;" />
                                                        </p>
							
							
						</div>
					</div>
					
					<p class="submit">
                                                <?php wp_nonce_field($this->onceAction) ?>					
						<input type="hidden" name="action" value="generate" />
						<input class="button-primary" type="submit" name="submit" value="Generate" />
					</p>
					
				</form>
				
			</div>
		</div>
	</div>
	
</div>
