<div class="help_troubleshooting" style="display:none;">

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label><?php echo __('Documentation & Tutorials', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wp2static.com" target="_blank">
          Official documentation and tutorials at wp2static.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-wordpress-alt"></span>
        <label><?php echo __('Ask a WordPress expert', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wordpress.stackexchange.com" target="_blank">
          https://wordpress.stackexchange.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-groups"></span>
        <label><?php echo __('Community', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://forum.wp2static.com/" target="_blank">
          Our support and development forum
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-format-chat"></span>
        <label><?php echo __('Community', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://t.me/wp2static" target="_blank">
          Chat for users & developers via Telegram
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-hammer"></span>
        <label><?php echo __('Report a bug', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://github.com/WP2static/wp2static/" target="_blank">
          Our project page on GitHub
        </a>
      </td>
    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

