<option value="mic_black_pinother_02.png"><?php _e('Pin #3','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_red_pinother_02.png"><?php _e('Pin #3','OSM-plugin');echo ' ';_e('red','OSM-plugin') ?></option>
<option value="mic_green_pinother_02.png"><?php _e('Pin #3','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_blue_pinother_02.png"><?php _e('Pin #3','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>  
<option value="wpttemp-green.png"><?php _e('Waypoint','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="wpttemp-red.png"><?php _e('Waypoint','OSM-plugin');echo ' ';_e('red','OSM-plugin') ?></option>
<option value="wpttemp-yellow.png"><?php _e('Waypoint','OSM-plugin');echo ' ';_e('yellow','OSM-plugin') ?></option>
<option value="wpttemp-blue.png"><?php _e('Waypoint','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="marker_blue.png"><?php _e('Marker','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>    
<option value="mic_black_camera_01.png"><?php _e('Camera','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option> 
<option value="mic_green_icecream_01.png"><?php _e('Icecream','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_blue_toilets_disability_01.png"><?php _e('Toilets disability','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_red_pizzaria_01.png"><?php _e('Pizzaria','OSM-plugin');echo ' ';_e('red','OSM-plugin') ?></option>
<option value="mic_green_horseriding_01.png"><?php _e('Horseriding','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_blue_cycling_01.png"><?php _e('Cycling','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_blue_information_01.png"><?php _e('Information','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_blue_horseriding_01.png"><?php _e('Horserinding','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_black_car_01.png"><?php _e('Car','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_brown_car_01.png"><?php _e('Car','OSM-plugin');echo ' ';_e('brown','OSM-plugin') ?></option>
<option value="mic_green_car_01.png"><?php _e('Car','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_green_caravan_01.png"><?php _e('Caravan','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_black_train_01.png"><?php _e('Train','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_steamtrain_01.png"><?php _e('Steamtrain','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_powerplant_01.png"><?php _e('Powerplant','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_parking_bicycle-2_01.png"><?php _e('Bicycle Parking','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_cctv_01.png"><?php _e('cctv','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_blue_toilets_01.png"><?php _e('Toilets','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_blue_scubadiving_01.png"><?php _e('Scubadiving','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_orange_motorbike_01.png"><?php _e('Motorbike','OSM-plugin');echo ' ';_e('orange','OSM-plugin') ?></option>
<option value="mic_orange_sailing_1.png"><?php _e('Sailing','OSM-plugin');echo ' ';_e('orange','OSM-plugin') ?></option>
<option value="mic_orange_fishing_01.png"><?php _e('Fishing','OSM-plugin');echo ' ';_e('orange','OSM-plugin') ?></option>
<option value="mic_blue_mobilephonetower_01.png"><?php _e('Mobilephonetower','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_orange_hiking_01.png"><?php _e('Hiking','OSM-plugin');echo ' ';_e('orange','OSM-plugin') ?></option>
<option value="mic_blue_bridge_old_01.png"><?php _e('Bridge','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_blue_drinkingwater_01.png"><?php _e('Drinkingwater','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_orange_archery_01.png"><?php _e('Archery','OSM-plugin');echo ' ';_e('orange','OSM-plugin') ?></option>
<option value="mic_black_archery_01.png"><?php _e('Archery','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_empty_01.png"><?php _e('Empty Marker','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_black_empty_01.png"><?php _e('Empty Marker','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_green_audio_01.png"><?php _e('Speaker','OSM-plugin');echo ' ';_e('green','OSM-plugin') ?></option>
<option value="mic_red_pirates_01.png"><?php _e('Pirates','OSM-plugin');echo ' ';_e('red','OSM-plugin') ?></option>
<option value="mic_black_heart_01.png"><?php _e('Heart','OSM-plugin');echo ' ';_e('black','OSM-plugin') ?></option>
<option value="mic_brown_harbor_01.png"><?php _e('Harbor','OSM-plugin');echo ' ';_e('brown','OSM-plugin') ?></option>
<option value="mic_blue_shower_01.png"><?php _e('Shower','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_brown_fillingstation_01.png"><?php _e('Fillingstation','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_blue_lighthouse-2_01.png"><?php _e('Lighthouse','OSM-plugin');echo ' ';_e('blue','OSM-plugin') ?></option>
<option value="mic_brown_parking_01.png"><?php _e('Parking','OSM-plugin');echo ' ';_e('brown','OSM-plugin') ?></option>
<option value="mic_green_palm-tree-export_01.png"><?php _e('Palm tree','OSM-plugin');echo ' ';_e('brown','OSM-plugin') ?></option>

<option value="geocache.png"><?php _e('Geocache','OSM-plugin') ?></option>
<option value="styria_linux.png"><?php _e('Styria Tux','OSM-plugin') ?></option>
