<option value="mic_black_pinother_02.png"><?php _e('Pin #3','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_red_pinother_02.png"><?php _e('Pin #3','OSM');echo ' ';_e('red','OSM') ?></option>
<option value="mic_green_pinother_02.png"><?php _e('Pin #3','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_blue_pinother_02.png"><?php _e('Pin #3','OSM');echo ' ';_e('blue','OSM') ?></option>  
<option value="wpttemp-green.png"><?php _e('Waypoint','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="wpttemp-red.png"><?php _e('Waypoint','OSM');echo ' ';_e('red','OSM') ?></option>
<option value="wpttemp-yellow.png"><?php _e('Waypoint','OSM');echo ' ';_e('yellow','OSM') ?></option>
<option value="wpttemp-blue.png"><?php _e('Waypoint','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="marker_blue.png"><?php _e('Marker','OSM');echo ' ';_e('blue','OSM') ?></option>    
<option value="mic_black_camera_01.png"><?php _e('Camera','OSM');echo ' ';_e('black','OSM') ?></option> 
<option value="mic_green_icecream_01.png"><?php _e('Icecream','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_blue_toilets_disability_01.png"><?php _e('Toilets disability','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_red_pizzaria_01.png"><?php _e('Pizzaria','OSM');echo ' ';_e('red','OSM') ?></option>
<option value="mic_green_horseriding_01.png"><?php _e('Horseriding','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_blue_cycling_01.png"><?php _e('Cycling','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_blue_information_01.png"><?php _e('Information','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_blue_horseriding_01.png"><?php _e('Horserinding','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_black_car_01.png"><?php _e('Car','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_brown_car_01.png"><?php _e('Car','OSM');echo ' ';_e('brown','OSM') ?></option>
<option value="mic_green_car_01.png"><?php _e('Car','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_green_caravan_01.png"><?php _e('Caravan','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_black_train_01.png"><?php _e('Train','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_steamtrain_01.png"><?php _e('Steamtrain','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_powerplant_01.png"><?php _e('Powerplant','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_parking_bicycle-2_01.png"><?php _e('Bicycle Parking','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_cctv_01.png"><?php _e('cctv','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_blue_toilets_01.png"><?php _e('Toilets','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_blue_scubadiving_01.png"><?php _e('Scubadiving','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_orange_motorbike_01.png"><?php _e('Motorbike','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_orange_sailing_1.png"><?php _e('Sailing','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_orange_fishing_01.png"><?php _e('Fishing','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_blue_mobilephonetower_01.png"><?php _e('Mobilephonetower','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_orange_hiking_01.png"><?php _e('Hiking','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_blue_bridge_old_01.png"><?php _e('Bridge','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_blue_drinkingwater_01.png"><?php _e('Drinkingwater','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_orange_archery_01.png"><?php _e('Archery','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_black_archery_01.png"><?php _e('Archery','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_empty_01.png"><?php _e('Empty Marker','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_black_empty_01.png"><?php _e('Empty Marker','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_green_audio_01.png"><?php _e('Speaker','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_red_pirates_01.png"><?php _e('Pirates','OSM');echo ' ';_e('red','OSM') ?></option>
<option value="mic_black_heart_01.png"><?php _e('Heart','OSM');echo ' ';_e('black','OSM') ?></option>
<option value="mic_brown_harbor_01.png"><?php _e('Harbor','OSM');echo ' ';_e('brown','OSM') ?></option>
<option value="mic_blue_shower_01.png"><?php _e('Shower','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_brown_fillingstation_01.png"><?php _e('Fillingstation','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_blue_lighthouse-2_01.png"><?php _e('Lighthouse','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_brown_parking_01.png"><?php _e('Parking','OSM');echo ' ';_e('brown','OSM') ?></option>
<option value="mic_green_palm-tree-export_01.png"><?php _e('Palm tree','OSM');echo ' ';_e('brown','OSM') ?></option>

<option value="mic_blue_ski_tour_01.png"><?php _e('Skitour','OSM');echo ' ';_e('blue','OSM') ?></option>
<option value="mic_green_tent_01.png"><?php _e('Tent','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_green_hut_01.png"><?php _e('Hut 01','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_green_hut_02.png"><?php _e('Hut 02','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_green_restaurant_02.png"><?php _e('Restaurant','OSM');echo ' ';_e('green','OSM') ?></option>
<option value="mic_orange_climbing_01.png"><?php _e('Climbing','OSM');echo ' ';_e('orange','OSM') ?></option>
<option value="mic_orange_van_01.png"><?php _e('Van','OSM');echo ' ';_e('orange','OSM') ?></option>

<option value="geocache.png"><?php _e('Geocache','OSM') ?></option>
<option value="styria_linux.png"><?php _e('Styria Tux','OSM') ?></option>
