<div class="wrap">
    <h2><?php _e('Tooltip Tags', 'cm-tooltip-glossary'); ?></h2>
    <?php CMTT_Free::cmtt_showNav(); ?>
    <div class="clear"></div>
<br>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">Enhance glossary navigation with tags. Use tags to connect related terms, allowing users to discover content easily and explore relevant topics.</p>
<br>
<div style="float:left; width:100%; margin-bottom:30px;">
    <div style="text-align:center; width:300px; float:left; margin-right:20px;">
        <a href="<?php echo  CMTT_PLUGIN_URL . 'assets/img/cm-tooltip-glossary-tags.png'; ?>" target="_blank" style="text-decoration:none;">
            <img src="<?php echo CMTT_PLUGIN_URL . 'assets/img/cm-tooltip-glossary-tags.png'; ?>" alt="" style="width:100%; border:1px solid #444;" />
        </a>
        <span style="font-size:15px;">Tags Dashboard</span>
    </div>
</div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Advanced tag management tools</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Customizable display for tagged terms</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Improved search functionality by tags</li>
</ul>
    <p style="font-size:16px;"><strong>Note:</strong> this feature is available only in Pro+ and higher versions</p>.
    <br>
<a href="<?php echo admin_url('admin.php?page=cmtt_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>