<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

wp_nonce_field( 'genesis_inpost_adsense_save', 'genesis_inpost_adsense_nonce' );
?>
<table class="form-table">
    <tbody>

    <tr valign="top">
        <th scope="row">
            <strong><?php esc_html_e( 'AdSense Output', 'genesis' ); ?></strong>
        </th>
        <td>
			<input type="hidden" name="genesis_adsense[key]" value="1" />
			<input type="checkbox" name="genesis_adsense[_disable_adsense]" id="genesis_adsense[_disable_adsense]" value="1" <?php checked( genesis_get_custom_field( '_disable_adsense' ) ); ?> />
			<label for="genesis_adsense[_disable_adsense]"><?php esc_html_e( 'Disable AdSense output for this entry?', 'genesis' ); ?></label>
        </td>
    </tr>

    </tbody>
</table>
