parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"CSIX":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TYPES=void 0;var e=wp,s=e.i18n.__,l=[{label:s("Newest","buddypress"),value:"newest"},{label:s("Active","buddypress"),value:"active"},{label:s("Popular","buddypress"),value:"popular"}];exports.TYPES=l;
},{}],"qXsY":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./constants"),t=wp,n=t.blockEditor.InspectorControls,o=t.components,r=o.Disabled,l=o.PanelBody,s=o.RangeControl,i=o.SelectControl,a=o.ToggleControl,d=t.element,u=d.Fragment,b=d.createElement,p=t.i18n.__,c=bp,f=c.blockComponents.ServerSideRender,m=c.blockData.currentPostId,g=function(t){var o=t.attributes,d=t.setAttributes,c=o.postId,g=o.maxFriends,k=o.friendDefault,C=o.linkTitle,v=m();return!c&&v&&d({postId:v}),b(u,null,b(n,null,b(l,{title:p("Settings","buddypress"),initialOpen:!0},b(s,{label:p("Max friends to show","buddypress"),value:g,onChange:function(e){return d({maxFriends:e})},min:1,max:10,required:!0}),b(i,{label:p("Default members to show","buddypress"),value:k,options:e.TYPES,onChange:function(e){d({friendDefault:e})}}),b(a,{label:p("Link block title to Member's profile friends page","buddypress"),checked:!!C,onChange:function(){d({linkTitle:!C})}}))),b(r,null,b(f,{block:"bp/friends",attributes:o})))},k=g;exports.default=k;
},{"./constants":"CSIX"}],"fch3":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=wp,r=e.blocks.createBlock,t={from:[{type:"block",blocks:["core/legacy-widget"],isMatch:function(e){var r=e.idBase,t=e.instance;return!(null==t||!t.raw)&&"bp_core_friends_widget"===r},transform:function(e){var t=e.instance;return r("bp/friends",{maxFriends:t.raw.max_friends,friendDefault:t.raw.friend_default,linkTitle:t.raw.link_title})}}]},a=t;exports.default=a;
},{}],"Z2R5":[function(require,module,exports) {
"use strict";var e=r(require("./friends/edit")),t=r(require("./friends/transforms"));function r(e){return e&&e.__esModule?e:{default:e}}var d=wp,i=d.blocks.registerBlockType,s=d.i18n.__;i("bp/friends",{title:s("Friends List","buddypress"),description:s("A dynamic list of recently active, popular, and newest friends of the post author (when used into a page or post) or of the displayed member (when used in a widgetized area). If author/member data is not available the block is not displayed.","buddypress"),icon:{background:"#fff",foreground:"#d84800",src:"buddicons-friends"},category:"buddypress",attributes:{maxFriends:{type:"number",default:5},friendDefault:{type:"string",default:"active"},linkTitle:{type:"boolean",default:!1},postId:{type:"number",default:0}},edit:e.default,transforms:t.default});
},{"./friends/edit":"qXsY","./friends/transforms":"fch3"}]},{},["Z2R5"], null)
//# sourceMappingURL=/bp-friends/js/blocks/friends.js.map