<style>
    div.cmtt-upgrade {
        display: inline-block;
        padding: 1em;
        background: #FFF;
        border: solid 1px #E0E0E0;
        max-width: 650px;
        margin: 1em 0;
    }
</style>

<div class="cmtt-upgrade">
    <h3>Want more? Get the PRO</h3>
    <p>Professional version of <?php echo CMTT_NAME; ?> which gives the admin better tools to customize the Glossary Tooltip system behavior:
        adding customization options, metaboxes, shortcodes, views, 3rd party integrations and a lot more.</p>
    <a href="<?php echo esc_attr(admin_url('admin.php?page=' . CMTT_PRO_OPTION)); ?>" class="button button-primary">Upgrade to PRO</a>
</div>