<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-widget-creation',
	'deps' => [
		'elementor-v2-editor',
		'elementor-v2-editor-mcp',
		'elementor-v2-editor-ui',
		'elementor-v2-events',
		'elementor-v2-icons',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
