parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"gOka":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TYPES=void 0;const{i18n:{__:e}}=wp,s=[{label:e("Newest","buddypress"),value:"newest"},{label:e("Active","buddypress"),value:"active"},{label:e("Popular","buddypress"),value:"popular"}];exports.TYPES=s;
},{}],"z0p7":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./constants");const{blockEditor:{InspectorControls:t},components:{Disabled:l,PanelBody:r,RangeControl:n,SelectControl:o,TextControl:s,ToggleControl:a},element:{Fragment:i,createElement:b},i18n:{__:u},serverSideRender:d}=wp,{blockData:{isActive:m}}=bp,c=c=>{let{attributes:p,setAttributes:v}=c;const{title:g,maxMembers:y,memberDefault:C,linkTitle:f}=p,k=m("friends")?e.TYPES:e.TYPES.filter(e=>"popular"!==e.value);return b(i,null,b(t,null,b(r,{title:u("Settings","buddypress"),initialOpen:!0},b(s,{label:u("Title","buddypress"),value:g,onChange:e=>{v({title:e})}}),b(n,{label:u("Max members to show","buddypress"),value:y,onChange:e=>v({maxMembers:e}),min:1,max:10,required:!0}),b(o,{label:u("Default members to show","buddypress"),value:C,options:k,onChange:e=>{v({memberDefault:e})}}),b(a,{label:u("Link block title to Members directory","buddypress"),checked:!!f,onChange:()=>{v({linkTitle:!f})}}))),b(l,null,b(d,{block:"bp/dynamic-members",attributes:p})))};var p=c;exports.default=p;
},{"./constants":"gOka"}],"qfGr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;const{blocks:{createBlock:e}}=wp,t={from:[{type:"block",blocks:["core/legacy-widget"],isMatch:e=>{let{idBase:t,instance:r}=e;return!(!r||!r.raw)&&"bp_core_members_widget"===t},transform:t=>{let{instance:r}=t;return e("bp/dynamic-members",{title:r.raw.title,maxMembers:r.raw.max_members,memberDefault:r.raw.member_default,linkTitle:r.raw.link_title})}}]};var r=t;exports.default=r;
},{}],"Znbi":[function(require,module,exports) {
"use strict";var e=r(require("./dynamic-members/edit")),t=r(require("./dynamic-members/transforms"));function r(e){return e&&e.__esModule?e:{default:e}}const{blocks:{registerBlockType:s},i18n:{__:d}}=wp;s("bp/dynamic-members",{title:d("Dynamic Members List","buddypress"),description:d("A dynamic list of recently active, popular, and newest members.","buddypress"),icon:{background:"#fff",foreground:"#d84800",src:"groups"},category:"buddypress",attributes:{title:{type:"string",default:d("Members","buddypress")},maxMembers:{type:"number",default:5},memberDefault:{type:"string",default:"active"},linkTitle:{type:"boolean",default:!1}},edit:e.default,transforms:t.default});
},{"./dynamic-members/edit":"z0p7","./dynamic-members/transforms":"qfGr"}]},{},["Znbi"], null)
//# sourceMappingURL=/bp-members/js/blocks/dynamic-members.js.map